---
driver_plugin: vagrant

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
  - name: data_bag
    run_list:
      - recipe[user::data_bag]
      - recipe[ssh_user::data_bag]
    attributes:
      users:
      - testman
